---
title: "A3SR Math Review"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Properties of Logarithms   
## Relevant Courses:  

  -Quantitative Methods  
  -Generalized Linear Models
  
## Notes    

### Definition  
Logarithms are defined such that $log_b(A)=X$ is equivalent to $b^X=A$  
   
### Properties  
Using properties of exponents and the definition above, we can derive the following:  

  a. The Product Rule: $log_b(MN)=log_b(M)+log_b(N)$  
  b. The Quotient Rule: $log_b(\frac{M}{N})=log_b(M)-log_b(N)$  
  c. The Power Rule: $log_b(M^p)=plog_b(M)$  
  d. $log_b(b^X)=X$  
  e. $b^{log_b(X)}=X$  
  f. $log_bb=1$   
  g. $log_b1=0$  
     
### Example 1: Expanding logarithms   
$log_e(\frac{2x^3}{y})$  
$=log_e(2x^3)-log_e(y)$  
$=log_e(2)+log_e(x^3)-log_e(y)$  
$=log_e(2)+3log_e(x)-log_e(y)$   
   
### Example 2: Condensing logarithms   
$2log_3(x)+log_3(5)-log_3(2)$   
$=log_3(x^2)+log_3(5)-log_3(2)$  
$=log_3(5x^2)-log_3(2)$     
$=log_3(\frac{5x^2}{2})$   

\pagebreak   
  
## Practice Problems   
  
  1. Solve the following:  
    a. $log_e(e^x)$  
    b. $log_{10}(100)$  
    c. $log_{10}(\frac{1}{10})$  
    d. $log_{10}(0)$   
   
  2. Expand the following:  
    a. $log_{10}(\frac{5y^3}{x})$    
    b. $log_{2}(\frac{4y^2}{3x})$  
    c. $log_e(2x^2y^3)$  
    
  3. Condense the following:  
    a. $4log_3(x)-2log_3(y)$  
    b. $log_2(x)+5log_2(y)-log_2(5)$  
    c. $log_{10}(5)+log_{10}(2)$   
   
## Answers    
  
  1. Solve:    
    a.  $x$  
    b.  $2$  
    c.  $-1$  
    d.  There is no solution because there is no power of $10$ that would equal $0$    
       
  2. Expand:    
    a.  $log_{10}(5) +3log_{10}(y)-log_{10}(x)$    
    b.  $2+2log_{2}(y)-log_{2}(3)-log_{2}(x)$   
    c. $log_e(2)+2log_e(x)+3log_e(y)$   
    
  3. Condense  
    a.  $log_3(\frac{x^4}{y^2})$   
    b.  $log_2(\frac{xy^5}{5})$  
    c.  $1$   
  
    
\pagebreak   
   
# Matrix Algebra  
## Relevant Courses:  

  -Quantitative Methods    

## Notes    
Note that these notes are a summary of relevant information from  https://www.math.psu.edu/bressan/PSPDF/M441-linalgebra_review.pdf   

### Definitions  
An $m\times n$ matrix $A$ has $m$ rows, $n$ columns, and can be written as:     
$$A=\begin{bmatrix}
a_{11}&a_{12}&...&a_{1n}\\
a_{21}&a_{22}&...&a_{2n}\\
...&...&...&...\\
a_{m1}&a_{m2}&...&a_{mn}\\
\end{bmatrix}$$

The transpose of an $m\times n$ matrix, $A$ is the $n\times m$ matrix (denoted $A^T$) such that every element $a_{ij}$ in matrix A is moved to row $j$ and column $i$. For example, if:  
$$A=\begin{bmatrix}
1&2&5\\
3&4&7\\
\end{bmatrix}$$  
then,  
$$A^T=\begin{bmatrix}
1&3\\
2&4\\
5&7\\
\end{bmatrix}$$  

The $n\times n$ identity matrix $I_n$ is a matrix with $1$s on the diagonal and $0$s everywhere else:  
$$I_n=\begin{bmatrix}
1&0&...&0\\
0&1&...&0\\
...&...&\ddots &...\\
0&0&...&1\\
\end{bmatrix}$$

An $n\times n$ matrix is called "diagonal" if all elements not on the diagonal are zeros. For example:  
$$\begin{bmatrix}
1&0&0\\
0&4&0\\
0&0&5\\
\end{bmatrix}$$
  
An $n\times n$ matrix is called "upper triangular" if all elements below the diagonal are zeros. For example:  
$$\begin{bmatrix}
1&0&1\\
0&4&2\\
0&0&4\\
\end{bmatrix}$$   
   
An $n\times n$ matrix is called "lower triangular" if all elements above the diagonal are zeros. For example:  
$$\begin{bmatrix}
1&0&0\\
1&4&0\\
0&4&4\\
\end{bmatrix}$$   
   
Suppose that an we have $2$ $n\times n$ matrices, $A$ and $B$, such that $AB=I_n$ (note: this also implies $BA=I_n$). Then we say that $B$ is the inverse of $A$ (and vice versa) and we can write, $B=A^{-1}$. A matrix $A$ has an inverse if and only if its determinant is not equal to zero. Note that the determinant of a $2\times 2$ matrix can be calculated as follows (it is not important that you are able to calculate the determinant of a higher dimensional matrix by hand):  
$$det(\begin{bmatrix}
a&b\\
c&d\\
\end{bmatrix})=ad-bc$$ 

### Operations with matrices  

  a. Adding matrices ($A+B=C$): If we add $2$ $m\times n$ matrices, $A$ and $B$, we get another $m\times n$ matrix $C$ such that $c_{ij}=a_{ij}+b_{ij}$  
  b. Subtracting matrices ($A-B=C$): If we subtract the $m\times n$ matrix $B$ from the $m\times n$ matrix $A$, we get another $m\times n$ matrix $C$ such that $c_{ij}=a_{ij}-b_{ij}$   
  c. Multiplying a matrix by a scalar ($cA=B$): If we multiply the $m\times n$ matrix $A$ by a scalar, $c$, then we get another $m\times n$ matrix $B$ such that $b_{ij}=c*a_{ij}$   
  d. Matrix multiplication ($AB=C$): Note that it is only possible to compute $AB$ if the number of columns in matrix $A$ equals the number of rows in matrix $B$. If this is the case, then when we multiply an $m\times n$ matrix $A$ by an $n\times k$ matrix $B$, we get an $m\times k$ matrix, $C$, such that $c_{ik}=a_{i1}b_{1k}+a_{i2}b_{2k}+\dots+a_{in}b_{nk}$   
  
### Example 1: Matrix Multiplication     
$$\begin{bmatrix}
3&4\\
2&5\\
1&2\\
\end{bmatrix}
\begin{bmatrix}
7&2&1\\
3&5&2\\
\end{bmatrix}=
\begin{bmatrix}
(3*7+4*3)&(3*2+4*5)&(3*1+4*2)\\
(2*7+5*3)&(2*2+5*5)&(2*1+5*2)\\
(1*7+2*3)&(1*2+2*5)&(1*1+2*2)\\
\end{bmatrix}=
\begin{bmatrix}
33&26&11\\
29&29&12\\
13&12&5\\
\end{bmatrix}$$

### Properties of matrix operations  
  a. $A+B=B+A$  
  b. $(A+B)+C=A+(B+C)$   
  c. $(AB)C=A(BC)$   
  d. $(A+B)C=AC + BC$  
  e. If $A$ is an $m\times n$ matrix, then $I_mA=A$ and $AI_n=A$
  
Note that, in general $AB \ne BA$   
\pagebreak  

### Writing a system of equations using matrix notation   
Note that, if we have a system of equations:  
$y_1=a_{11}x_1+a_{12}x_2+\dots+a_{1n}x_n$  
$y_2=a_{21}x_1+a_{22}x_2+\dots+a_{2n}x_n$  
...  
$y_m=a_{m1}x_1+a_{m2}x_2+\dots+a_{mn}x_n$  

We can re-write these equations much more simply as:  
$Y=AX$ where $Y$is a $1\times m$ matrix, $A$ is an $m\times n$ matrix, and $X$ is a $1\times n$ matrix:  

$$\begin{bmatrix}
y_1\\
y_2\\
.\\
.\\
.\\
y_n\\
\end{bmatrix}=
\begin{bmatrix}
a_{11}&a_{12}&...&a_{1n}\\
a_{21}&a_{22}&...&a_{2n}\\
...&...&...&...\\
a_{m1}&a_{m2}&...&a_{mn}\\
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
.\\
.\\
.\\
x_n\\
\end{bmatrix}
$$
    
  
\pagebreak   
  
## Practice Problems   
  
  1. Solve the following:  
    a. $\begin{bmatrix}
2&4&2\\
1&3&0\\
1&6&2\\
\end{bmatrix}+
\begin{bmatrix}
1&5&0\\
-2&-3&0\\
1&9&5\\
\end{bmatrix}$     
    b. $\begin{bmatrix}
2&1\\
-2&2\\
4&2\\
\end{bmatrix}
\begin{bmatrix}
5&2&-1\\
3&4&2\\
\end{bmatrix}$      
    c. Let A=$\begin{bmatrix}
1&2\\
3&5\\
4&0\\
\end{bmatrix}$ and 
$B=\begin{bmatrix}
4&4\\
1&2\\
7&0\\
\end{bmatrix}$ Calculate $A^TB$   
    d. Using the same matrices as in part c, calculate $B^TA$         
   
  2. Show that $A$ and $B$ are inverses:   
     $A=\begin{bmatrix}
1&2&1\\
2&2&0\\
1&1&1\\
\end{bmatrix}$    
$B=\begin{bmatrix}
-1&0.5&1\\
1&0&-1\\
0&-0.5&1\\
\end{bmatrix}$   

  3. Suppose that $A$ is a 4x3 matrix and $B$ is a $3x8$ matrix.  
    a. Does $AB$ exist? If so, what are the dimensions of $AB$?  
    b. Does $BA$ exist? If so, what are the dimensions of $BA$?  
    
  4. What is the determinant of $\begin{bmatrix}
1&-2\\
4&3\\
\end{bmatrix}$?   

   
## Answers    
  
  1. Solve:    
    a.  $\begin{bmatrix}
3&9&2\\
-1&0&0\\
2&15&7\\
\end{bmatrix}$    
    b.  $\begin{bmatrix}
13&8&0\\
-4&4&6\\
26&16&0\\
\end{bmatrix}$   
    c.  $\begin{bmatrix}
35&10\\
13&18\\
\end{bmatrix}$   
    d.  $\begin{bmatrix}
35&13\\
10&18\\
\end{bmatrix}$      
       
  2. Show that $A$ and $B$ are inverses:    
  $\begin{bmatrix}
1&2&1\\
2&2&0\\
1&1&1\\
\end{bmatrix}  
\begin{bmatrix}
-1&0.5&1\\
1&0&-1\\
0&-0.5&1\\
\end{bmatrix}=\begin{bmatrix}
1&0&0\\
0&1&0\\
0&0&1\\
\end{bmatrix}$
  
  3. Suppose that $A$ is a 4x3 matrix and $B$ is a $3x8$ matrix.  
    a. $AB$ exists and is 4x8   
    b. $BA$ does not exist    
    
  4. The determinant is $(1*3)-(-2*4)=(3)-(-8)=11$   
  
\pagebreak  

# Derivatives   
## Relevant Courses:  

  -Probability  
  -Quantitative Methods   
  
## Notes   

### Definition  
The derivative of a function $y=f(x)$ with respect to $x$ is defined as a function giving the instantaneous slope of $y=f(x)$ for any value $x$. Notationally, a derivative can be written in any of the following ways:  
$$f'(x)=y'=\frac{df}{dx}=\frac{d}{dx}(f(x))=\frac{dy}{dx}=\frac{d}{dx}(y)$$
  
### Using derivatives to find local minima and maxima of a function  
To find all local minima or maxima of a function $y=f(x)$:    
  1) Take the first derivative of $f(x)$ with respect to x ($f'(x)$).  
  2) Set this expression equal to zero and solve for x. These values of x are local maxima and minima.   
  3) Calculate the second derivative of $f(x)$ with respect to x ($f''(x)$)  
  4) Plug in the values of x calculated in part 2. If the second derivative is positive, this value of x represents a local minimum; if the second derivative is negative, it is a local maximum    
  
## Properties   

Properties of derivatives:  
  1) Sum/Difference rule: $(f(x)\pm g(x))'=f'(x)\pm g'(x)$  
  2) Constant multiple rule: $(cf(x))'=cf'(x)$ where $c$ is a constant  
  3) Product rule: $(f(x)g(x))' = f'(x)g(x) + g'(x)f(x)$
  \newline
  4) Quotient rule (given g(x) != 0): $(\frac{f(x)}{g(x)})' = \frac{f'(x)g(x) - g'(x)f(x)}{g^2(x)}$
  \newline
  5) Chain rule: $(f(g(x)))' = f'(g(x)) * g'(x)$
  

\pagebreak
  
## Practice Problems   
  
  1. Solve the following:  
    a. 

   
## Answers    
  
  1. Solve:    
    a.  

  
\pagebreak    

# Integrals   
## Relevant Courses:  

  -Probability  
  -Quantitative Methods  

## Notes  

\pagebreak
  
## Practice Problems   
  
  1. Solve the following:  
    a. 

   
## Answers    
  
  1. Solve:    
    a.  

\pagebreak  

# Summary Statistics   
## Relevant Courses:  

  -Probability  
  -Quantitative Methods  
  -Statistical Computing  
  
\pagebreak  
  
# P-Values and T-Tests   
## Relevant Courses:  

  -Quantitative Methods    
  -Statistical Computing  
  -Causal Inference  
  
\pagebreak  
  
# Correlation and Covariance   
## Relevant Courses:  

  -Quantitative Methods   
  -Probability   
  
## Notes  


  
\pagebreak  
  
# Ordinary Least Squares Regression   
## Relevant Courses:  

  -Quantitative Methods   
\pagebreak  

# Probability Density/Mass Functions  
## Relevant Courses:  

  -Quantitative Methods   
  -Probability  
  -Causal Inference  
\pagebreak  
  
# Expectation  
## Relevant Courses:  

  -Probability   

  




